### ISSUE TITLE
add the usage of yarn as alternative

### ISSUE THREAD

**Issue by samvloeberghs** [samvloeberghs/protractor-gherkin-cucumberjs-angular#42]
consider switching definitely

**Comment by samvloeberghs** [comment]
@DennisJaamann you recently told me you we're on this? How is progressing? Can I help?

**Comment by DennisJaamann** [comment]
I think this story is obsolete since the arrival of node 8 + npm 5. There is now also a lock file generated for each project and it works very much the same way as yarn. My guess is yarn will slowly come to its end.

**Comment by samvloeberghs** [comment]
they seem to be even faster.. so indeed closing up
