### ISSUE TITLE
Add unit tests for the components

### ISSUE THREAD

**Issue by samvloeberghs** [samvloeberghs/protractor-gherkin-cucumberjs-angular#7]
The following services / validators / components / ... need to get unit tested:

First implement coverage, see : 
https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/issues/31
- [ ] authentication service
- [ ] email.validator
- [ ] forgotPassword.component
- [ ] login.component
- [ ] register.component
- [ ] setNewPassword.component
- [ ] app.component
- [ ] speakerRegistrationStepOne.component
- [ ] speakerRegistrationStepTwo.component
- [ ] speakerRegistrationStepThree.component

**Comment by Fiontan** [comment]
@samvloeberghs I have started adding unit tests to the pieces listed above. I have added istanbul to my project too so #31 is also covered. It would be useful if you could review the angular 4 version I have given you access to on bitbucket before I proceed any further :)

**Comment by samvloeberghs** [comment]
@Fiontan received the invite.. looking for time to allocate :) probably this weekend

**Comment by samvloeberghs** [comment]
not in scope of this project..
